version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/erlang:22.0"

    steps:
      - checkout
      - run:
          name: "Run dialyzer"
          command: |
            make dialyzer
      - run:
          name: "Run tests"
          command: |
            make test
